### ISSUE TITLE
I just cloned the repo, then run `npm install` it shows errors

### ISSUE THREAD

**Issue by nur-sasongko** [Bagus-BW/Boilerplate-ExpressJS#1]
npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: express-template-server@1.0.0
npm error Found: eslint@9.8.0
npm error node_modules/eslint
npm error   dev eslint@"^9.8.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer eslint@"^8.56.0" from typescript-eslint@7.18.0
npm error node_modules/typescript-eslint
npm error   dev typescript-eslint@"^7.18.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution
![Screenshot from 2024-08-01 21-32-27](https://github.com/user-attachments/assets/59e79838-c30a-4da6-9ce9-64ab31fdddc0)

**Comment by Bagus-BW** [comment]
solved, please pull the code in newest main remote branch
